#!/bin/bash
#
# ci_post_clone.sh
# Xcode Cloud - Runs after cloning the repository
#
# Generates xcconfig files from Xcode Cloud environment variables.
# The xcconfig files are gitignored (contain secrets), so CI must recreate them.
#

set -eo pipefail

echo "=== ci_post_clone: Generating xcconfig files from environment variables ==="

# Resolve paths relative to the script location
# ci_scripts/ is inside the Xcode project folder (onera-ios/ci_scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
XCCONFIG_DIR="${PROJECT_DIR}/Onera"

echo "  Script dir: ${SCRIPT_DIR}"
echo "  Project dir: ${PROJECT_DIR}"
echo "  XCConfig dir: ${XCCONFIG_DIR}"

# --- Production.xcconfig ---
# Used by Release builds (App Store / TestFlight)

PROD_CONFIG="${XCCONFIG_DIR}/Production.xcconfig"

echo "Generating Production.xcconfig..."

cat > "${PROD_CONFIG}" <<XCEOF
// Production.xcconfig
// Auto-generated by Xcode Cloud ci_post_clone.sh
// DO NOT COMMIT - this file is gitignored

// API Configuration
API_BASE_URL = https:/\$()/api.onera.chat
TRPC_PATH = /trpc

// Supabase Configuration
SUPABASE_URL = ${PROD_SUPABASE_URL:-https://your-production-project.supabase.co}
SUPABASE_ANON_KEY = ${PROD_SUPABASE_ANON_KEY:-sb_publishable_MISSING}

// WebAuthn Configuration
WEBAUTHN_RP_ID = ${PROD_WEBAUTHN_RP_ID:-onera.chat}
WEBAUTHN_RP_NAME = ${PROD_WEBAUTHN_RP_NAME:-Onera}

// Keychain Configuration
KEYCHAIN_SERVICE_NAME = ${PROD_KEYCHAIN_SERVICE_NAME:-chat.onera.keychain}

// Bundle Identifiers
PRODUCT_BUNDLE_IDENTIFIER = ${PROD_BUNDLE_IDENTIFIER:-chat.onera}
WATCHOS_BUNDLE_IDENTIFIER = ${PROD_WATCHOS_BUNDLE_IDENTIFIER:-chat.onera.watch}
IOS_BUNDLE_IDENTIFIER = ${PROD_BUNDLE_IDENTIFIER:-chat.onera}

// Display Name
DISPLAY_NAME = Onera
XCEOF

echo "  -> ${PROD_CONFIG}"

# --- Staging.xcconfig ---
# Used by Debug builds. Xcode Cloud builds Release, but the project
# references both configs so both must exist to avoid build errors.

STAGING_CONFIG="${XCCONFIG_DIR}/Staging.xcconfig"

echo "Generating Staging.xcconfig (placeholder for Debug config)..."

cat > "${STAGING_CONFIG}" <<XCEOF
// Staging.xcconfig
// Auto-generated by Xcode Cloud ci_post_clone.sh
// Placeholder - CI builds use Release (Production.xcconfig)

// API Configuration
API_BASE_URL = https:/\$()/api-stage.onera.chat
TRPC_PATH = /trpc

// Supabase Configuration
SUPABASE_URL = ${STAGING_SUPABASE_URL:-https://sencyalduvdmsnegrliy.supabase.co}
SUPABASE_ANON_KEY = ${STAGING_SUPABASE_ANON_KEY:-sb_publishable_BFcnpmS77VNAkySvsaxTWQ_Afcl3usA}

// WebAuthn Configuration
WEBAUTHN_RP_ID = staging.onera.chat
WEBAUTHN_RP_NAME = Onera Staging

// Keychain Configuration
KEYCHAIN_SERVICE_NAME = chat.onera.staging.keychain

// Bundle Identifiers
PRODUCT_BUNDLE_IDENTIFIER = chat.onera.staging
WATCHOS_BUNDLE_IDENTIFIER = chat.onera.staging.watch
IOS_BUNDLE_IDENTIFIER = chat.onera.staging

// Display Name
DISPLAY_NAME = Onera Staging
XCEOF

echo "  -> ${STAGING_CONFIG}"

# --- Verify ---
echo ""
echo "=== Verifying generated files ==="
for f in "${PROD_CONFIG}" "${STAGING_CONFIG}"; do
    if [ -f "$f" ]; then
        echo "  OK: $(basename "$f")"
    else
        echo "  MISSING: $f"
        exit 1
    fi
done

echo ""
echo "=== ci_post_clone: Done ==="
