#!/bin/bash
#
# ci_post_clone.sh
# Xcode Cloud - Runs after cloning the repository
#
# Generates xcconfig files from Xcode Cloud environment variables.
# The xcconfig files are gitignored (contain secrets), so CI must recreate them.
#
# NOTE: Clerk keys contain '$' which Xcode Cloud env vars don't support.
# Store them as base64-encoded values in PROD_CLERK_KEY_B64 / STAGING_CLERK_KEY_B64.
# To encode: echo -n 'pk_live_xxxxx' | base64
#

set -euo pipefail

echo "=== ci_post_clone: Generating xcconfig files from environment variables ==="

# Resolve paths relative to the workspace
# Xcode Cloud sets CI_WORKSPACE to the repo root
XCCONFIG_DIR="${CI_WORKSPACE}/Onera/Onera"

# --- Decode base64-encoded secrets ---

PROD_CLERK_KEY="pk_live_MISSING"
if [ -n "${PROD_CLERK_KEY_B64:-}" ]; then
    PROD_CLERK_KEY=$(echo "${PROD_CLERK_KEY_B64}" | base64 --decode)
    echo "  Decoded PROD_CLERK_KEY_B64"
fi

STAGING_CLERK_KEY="pk_test_placeholder"
if [ -n "${STAGING_CLERK_KEY_B64:-}" ]; then
    STAGING_CLERK_KEY=$(echo "${STAGING_CLERK_KEY_B64}" | base64 --decode)
    echo "  Decoded STAGING_CLERK_KEY_B64"
fi

# --- Production.xcconfig ---
# Used by Release builds (App Store / TestFlight)

PROD_CONFIG="${XCCONFIG_DIR}/Production.xcconfig"

echo "Generating Production.xcconfig..."

cat > "${PROD_CONFIG}" <<XCEOF
// Production.xcconfig
// Auto-generated by Xcode Cloud ci_post_clone.sh
// DO NOT COMMIT - this file is gitignored

// API Configuration
API_BASE_URL = https:/\$()/api.onera.chat
TRPC_PATH = /trpc

// Clerk Configuration
CLERK_PUBLISHABLE_KEY = ${PROD_CLERK_KEY}

// WebAuthn Configuration
WEBAUTHN_RP_ID = ${PROD_WEBAUTHN_RP_ID:-onera.chat}
WEBAUTHN_RP_NAME = ${PROD_WEBAUTHN_RP_NAME:-Onera}

// Keychain Configuration
KEYCHAIN_SERVICE_NAME = ${PROD_KEYCHAIN_SERVICE_NAME:-chat.onera.keychain}

// Bundle Identifiers
PRODUCT_BUNDLE_IDENTIFIER = ${PROD_BUNDLE_IDENTIFIER:-chat.onera}
WATCHOS_BUNDLE_IDENTIFIER = ${PROD_WATCHOS_BUNDLE_IDENTIFIER:-chat.onera.watchkitapp}
IOS_BUNDLE_IDENTIFIER = ${PROD_BUNDLE_IDENTIFIER:-chat.onera}

// Display Name
DISPLAY_NAME = Onera
XCEOF

echo "  -> ${PROD_CONFIG}"

# --- Staging.xcconfig ---
# Used by Debug builds. Xcode Cloud builds Release, but the project
# references both configs so both must exist to avoid build errors.

STAGING_CONFIG="${XCCONFIG_DIR}/Staging.xcconfig"

echo "Generating Staging.xcconfig (placeholder for Debug config)..."

cat > "${STAGING_CONFIG}" <<XCEOF
// Staging.xcconfig
// Auto-generated by Xcode Cloud ci_post_clone.sh
// Placeholder - CI builds use Release (Production.xcconfig)

// API Configuration
API_BASE_URL = https:/\$()/api-stage.onera.chat
TRPC_PATH = /trpc

// Clerk Configuration
CLERK_PUBLISHABLE_KEY = ${STAGING_CLERK_KEY}

// WebAuthn Configuration
WEBAUTHN_RP_ID = staging.onera.chat
WEBAUTHN_RP_NAME = Onera Staging

// Keychain Configuration
KEYCHAIN_SERVICE_NAME = chat.onera.staging.keychain

// Bundle Identifiers
PRODUCT_BUNDLE_IDENTIFIER = chat.onera.staging
WATCHOS_BUNDLE_IDENTIFIER = chat.onera.staging.watchkitapp
IOS_BUNDLE_IDENTIFIER = chat.onera.staging

// Display Name
DISPLAY_NAME = Onera Staging
XCEOF

echo "  -> ${STAGING_CONFIG}"

# --- Verify ---
echo ""
echo "=== Verifying generated files ==="
for f in "${PROD_CONFIG}" "${STAGING_CONFIG}"; do
    if [ -f "$f" ]; then
        echo "  OK: $(basename "$f")"
    else
        echo "  MISSING: $f"
        exit 1
    fi
done

echo ""
echo "=== ci_post_clone: Done ==="
